### PR TITLE
Stop disk caching most resources

### LINKED ISSUE #414: `.js` representation of note isn't deleted when note is
1. Create a public note
2. Navigate to the canonical version of the URL to confirm it exists (e.g., https://www.documentcloud.org/documents/282753-lefler-thesis/annotations/42281.html)
3. Change the `.html` to `.js` to warm the cache
4. Delete the note
5. Go to the `.html`, `.json`, and `.js` versions of the note
6. ✅ `.html/.json` correctly 404, but :x: `.js` incorrectly returns the data

### PR DESCRIPTION
**Pull request by reefdog**
With our nginx proxy caching (#369), disk caching docs, annotations, etc. is no longer necessary or preferred. As @knowtheory notes, we may one day want to reintroduce a more granular cache than our current proxy cache.

- [x] Disable defunct `cache_page` and `expire_page` statements
- ~Investigate replacement for [featured document](https://github.com/documentcloud/documentcloud/blob/d97dc5690cd0fe1f262fd1fc6d16912e64dbd3fc/app/controllers/home_controller.rb#L14)~ 👈  fine for now
- ~Investigate replacement for [admin stats JSON](https://github.com/documentcloud/documentcloud/blob/a840694c0bd2be27be2b6accad5a24553a872472/app/controllers/admin_controller.rb#L59-L70)~ 👈  moved to #427
- ~Disable various cache store settings~ 👈  part of #427
- ~Remove actionpack-page_caching gem~ 👈  part of #427
-----------------
- [x] Remove document cache (`/public/documents`)
- [ ] Remove [cache-clearing tasks](https://github.com/documentcloud/documentcloud/blob/8c5af063f31a47b10231590b41dddac522e9ec56/lib/tasks/app.rake#L80-L100) from [deploy tasks](https://github.com/documentcloud/documentcloud/blob/48952a1c11a127ea2ac49d02112aa8ec0beeb6d8/lib/tasks/deploy.rake#L9-L17)
- [ ] Close #414

### CODE REVIEW

**Comment by jashkenas** [comment]
This is fantastic — and can certainly remove a bunch of complexity ... to not be managing cached files on disk.

Just a quick safety check — You've got the nginx proxy caching correctly set up to expire public cached documents whenever they're updated? And there's only a single caching proxy where that expiration happens?

**Comment by reefdog** [comment]
> Just a quick safety check — You've got the nginx proxy caching correctly set up to expire public cached documents whenever they're updated? And there's only a single caching proxy where that expiration happens?

@knowtheory is probably typing up a longer and more accurate comment than this, but in summary: the proxy cache is a 10 second cache of every URL, unless the request is from an authenticated person (i.e. includes a session key). Sending explicit expiration commands from the platform was proving difficult (and expensive, I believe, as nginx seems to reserve that for a paid product), so it was punted. So not, it's not expired when updated, but it is expired every 10 seconds.

Aside: this does create an unfortunate race condition between the CDN access control changes and the proxy cache expiration. I've gone to the public search page and seen documents with broken images, because they had just been made private and the CDN had already updated its access controls but nginx was still serving the cached search page.

**Comment by knowtheory** [comment]
Yep!  definitely appreciate the sanity check (i wrote up some description of the outcomes here: https://github.com/documentcloud/documentcloud/issues/296#issuecomment-256179930 )

The platform is still being run as a Passenger service through the NGINX plugin.  The main platform responds to localhost on a particular port.   As part of that same NGINX setup, documentcloud.org terminates into the reverse proxy cache which connects to localhost.

Unfortunately nginx only provides the ability to expire/evict particular keys if you either pay for NGINX Plus or use a fairly complex 3rd party plugin system, so, for the time being, caching is done _unconditionally_ for public resources with [a 10 second cache](https://github.com/documentcloud/documentcloud/blob/master/app/controllers/application_controller.rb#L65)  (worth noting that we're also doing essentially the same thing with Cloudfront w/ a 30 sec window for expiry).

[We're current caching search results for longer](https://github.com/documentcloud/documentcloud/blob/master/app/controllers/search_controller.rb#L9) since requests are so resource intensive.  That can be dialed back once we improve search response times.

**Comment by knowtheory** [comment]
Oh, and yes, currently everything is going through a single server and proxy, so no inconsistency between repeated requests.  If we were to move to multiple backend machines, we'd still go through a single reverse proxy cache machine, and roundrobin backends for the proxy.

**Comment by reefdog** [comment]
Note to self: after merging/deploying this, rm the document disk cache.

**Comment by reefdog** [comment]
Okay, this is ready for review and merge. We can wait until Monday.

**Comment by reefdog** [comment]
This branch is currently in production and we're monitoring it for problems. After a few good days, we'll merge it into master.

**Comment by knowtheory** [comment]
things're looking good :)

**Pull request merged**
