### PR TITLE
Open Calais v2 upgrade

### PR DESCRIPTION
**Pull request by cometman**
Upgrades DC to utilize the new Open Calais v2 API. Ref ticket: https://github.com/documentcloud/documentcloud/issues/177

### Overview of changes that took place:
  - Build out testing infrastructure to support better testing (VCR, FactoryGirl)
  - Increase unit testing code coverage of existing Open Calais implementation
  - Transition to new Open Calais library with 2.0 support (https://github.com/PRX/open_calais)
  - Make unit tests pass again after migration!

### Remaining Tasks
  - Ensure entity & occurrences are "counted" in the same way by comparing a document with old & new entity extraction. 
  - We need to keep track of the number of requests being sent to Open Calais and furthermore, implement some sort of throttling to ensure we don't go over the daily rate limit.

Larger discussions about how jobs are processed and decoupling them from the application also need to take place.

### CODE REVIEW

**Comment by knowtheory** [comment]
OKAY!  Awesome @cometman!

For clarity's sake i'm going to recap:

DocumentCloud is switching into the new Calais API.  We should take this as an opportunity to begin refactoring the way that document processing is done (and add things in like a rate limit cap).

As of right now [document process](https://github.com/documentcloud/documentcloud/blob/master/app/actions/document_import.rb) is broken into two parts, [image processing](https://github.com/documentcloud/documentcloud/blob/b3c6badc9f5b134c09daacb6aa6c2ae9559c22cf/app/actions/document_import.rb#L72-L83) and [text processing](https://github.com/documentcloud/documentcloud/blob/b3c6badc9f5b134c09daacb6aa6c2ae9559c22cf/app/actions/document_import.rb#L85-L134).  Text processing includes [entity extraction](https://github.com/documentcloud/documentcloud/blob/b3c6badc9f5b134c09daacb6aa6c2ae9559c22cf/app/actions/document_import.rb#L128-L131).

Entity extraction should be pulled out of the main document import process, and instead turned into its own action that can be run independently.

--------------------------

We've got a couple overarching reasons to refactor entity extraction:

1. breaking entity extraction out as a general process, independent of uploading a document.
2. reworking the lifecycle of documents and the way they're imported
3. adding global request caps to jobs.

**Comment by knowtheory** [comment]
The current way that document importing works is for the `Document.upload` method to be called with appropriate metadata, which creates a `Document` record, which in turns makes a decision about what job to initiate, and then sends the job request off to CloudCrowd.

CloudCrowd then creates a `Job` record (which in turn creates `WorkUnit`s).  CloudCrowd dispatches `WorkUnit`s to `Node`s to perform.  `Node`s then start a `Worker` process that instantiates the `Job`'s `Action`, and runs the appropriate method from the `Action` instance.

That's where all the action actually takes place.

**Comment by knowtheory** [comment]
Intermediate Goals:

- [ ] Create a `extract_calais_entities` Action (see the other actions in `app/actions`)
- [ ] Remove entity extraction from the `document_import` action
- [ ] Add method to `Document` class to initiate entity extraction.
- [ ] Plan mechanism to enable/disable Calais entity extraction.
- [ ] Write up description of how requests to Calais are allocated (This is just queue insertion order right now).

**Comment by knowtheory** [comment]
Okay!  The current state of play...

This is getting merged, and additional changes and upgrades will head directly into master.

This pull request includes a variety of changes that stripe a cross a couple of repositories:

* CloudCrowd now has a facility for blacklisting actions, to ensure that work on blacklisted jobs will not be performed.  (And has ReST-y endpoints to POST to and DELETE from the list)
* Integration of PRX's `open_calais` gem, which as it turns out, deletes entity occurrences that are direct matches.  We want all of the entities and their location.  As such we have forked and patched the gem.
* Most of the groundwork we need in order to automatically blacklist entity processing after a certain number of calls have been made.

**Comment by knowtheory** [comment]
## Instructions on upgrading

Platform implementers will need to do two things:
* Ensure that `secrets/secrets.yml` includes a `:calais_license` (your API key) and a `:calais_api_limit` (the number of requests your key is allowed to make).
* Regenerate your cloud-crowd database (which can be done like so: `bin/crowd load_schema -c config/cloud_crowd/[YOUR ENV GOES HERE]` from the app root)

**Comment by knowtheory** [comment]
Remaining work for phase 1:

- [ ] Wire up calais request counting to initiating blacklisting of entity processing jobs.
- [ ] Verify that blacklist of entity processing jobs is cleared via rake task (and added to cron rake tasks).
- [ ] decouple entity extraction from document processing all together and repurpose `reprocess_entities` cloud-crowd action as `process_entities`.

**Comment by cometman** [comment]
`decouple_entity_processing` has been merged into master and entity extraction has been validated as working with the new cloud-crowd action name change.

**Pull request merged**
