### PR TITLE
Automate WordPress blog feed in site sidebar

### PR DESCRIPTION
**Pull request by anthonydb**
This pulls the most recent seven posts from our blog's API.

### CODE REVIEW

**Comment by knowtheory** [comment]
Cool beans :)

I would be hesitant to merge this primarily for one reason, which is that it's making a net request to the blog every time the action runs.  If /home started getting a lot of traffic the ability of the passengers to keep up would depend on each one fetching data.

There are two ways we could address this, we could fetch and cache the data in rails and figure out how/when expire the cache (although we'd have to figure out how to trigger the expiry), or we could see about pushing this forward into javascript and do the fetching client side, so that the passengers don't have to worry about handling that.

**Comment by anthonydb** [comment]
Possible Rails caching solution here?
http://stackoverflow.com/questions/5460862/caching-twitter-api-calls-in-rails

**Comment by knowtheory** [comment]
We're using rails's [FileStore caching functionality](http://guides.rubyonrails.org/caching_with_rails.html), so if we wanted to stash the assembled HTML, that'd be one way to go.  With rails's caching mechanism, we still have to figure out how to expire based on when a new post is published or some proxy thereof.

One ugly hacky way would be to have a cronjob which periodically checks whether new posts have been posted (but even if we were to post every day, having a cronjob that runs at regular intervals seems like a lot of unnecessary work.  Another would be to give our blog posting mechanisms some way to signal the platform to expire the cache (say have a Rails action for a url which the blog could POST to w/ a shared secret when a new post goes live.  Although i have no idea how complicated implementing this is from the WP side).

The js thing would be the other alternative (although that'd increase the # of requests to the WP blog too)

**Comment by reefdog** [comment]
Fetching client-side plus ensuring WP caches the JSON view would indeed be a quick win, if not the ideal one. Happy to whip it up.

**Comment by anthonydb** [comment]
Closing in favor of @reefdog's JS-based solution coming up.

**Pull request closed without merging**
