### PR TITLE
Serve iframes from oembed endpoint

### PR DESCRIPTION
**Pull request by knowtheory**
This branch makes it possible to embed DocumentCloud resources within iframes as an intentional and supported matter.

### CODE REVIEW

**Comment by reefdog** [comment]
This PR feeds iframed pages and notes to the oembed endpoint. Still working out some document kinks, but this should be deployable with docs coming soon.

**Comment by reefdog** [comment]
Daaaang it, I screwed up. :|

**Comment by esthervillars** [comment]
Big diff indeed
https://github.com/documentcloud/documentcloud/compare/master...iframe-oembed

**Comment by knowtheory** [comment]
I may force push to fix this

**Comment by reefdog** [comment]
> Big diff indeed
Yeah :(

**Comment by knowtheory** [comment]
Yeah having read up on this a little i'm going to have to close this in favor of another pull request.  sorry :\

**Pull request closed without merging**
